### ISSUE TITLE
Update installation procedure and troubleshooting

### ISSUE THREAD

**Issue by ted-miller** [Yaskawa-Global/motoros2#100]
In regard to https://github.com/ros-industrial/motoman/discussions/562#discussioncomment-6482427
We need to update the order of operations during setup and add a step to the troubleshooting. 

This is the same as https://github.com/ros-industrial/motoman/issues/563 for MotoROS1.

**Comment by gavanderhoorn** [comment]
> We need to update the order of operations during setup and add a step to the troubleshooting.

Could you clarify what exactly would need to be changed?

**Comment by ted-miller** [comment]
`CRC CHECK FUNC` needs to be disabled before loading the .out file. Then it can be reenabled after the Speed-Feedback alarm.

**Comment by gavanderhoorn** [comment]
@ted-miller: could you make the changes you describe?

Together with a fix for #54, this would be the last open issue for [0.1.1](https://github.com/Yaskawa-Global/motoros2/milestone/2).
