### ISSUE TITLE
Document current state of support for FSU

### ISSUE THREAD

**Issue by gavanderhoorn** [Yaskawa-Global/motoros2#156]
As evidenced by #155, the fact the FSU/PFL can interfere with trajectory execution by MotoROS2 is not obvious to users.

We have an open issue tracking this (#50), but that's not user-facing documentation.

We should add a section to the [Known issues & limitations](https://github.com/Yaskawa-Global/motoros2/tree/bd95e65679d582b13b3887e5277d34f7406db69a#known-issues--limitations) section instead.

Refer to #50 in the new section, to keep discussion centralised, but clarify FSU/PFL support in MotoROS2 in the text itself.

**Comment by gavanderhoorn** [comment]
@ted-miller: could you address this now that you've merged #155?

In the absence of a ROS API for "FSU status" (#50), documentation is the next best thing, and #155 changed the default behaviour of MotoROS2.

**Comment by ted-miller** [comment]
Sure. Just gimme a few days to finish up some other tasks.

**Comment by ted-miller** [comment]
I removed PFL from the title of this issue.
We haven't done any PFL testing on an HC. I'm concerned because PFL can not only limit robot motion, but also generate motion.
