### ISSUE TITLE
Unexpected `8011[63]` (`Invalid motion type`) (YRC, GP25, linear track)

### ISSUE THREAD

**Issue by gavanderhoorn** [Yaskawa-Global/motoros2#178]
It looks like #176 works a little too well, in that it immediately is raised on a YRC1, GP25 on a linear track -- which is a simple system that should-just-work (tm).

Have to investigate.

**Comment by gavanderhoorn** [comment]
@ted-miller: is `MOTION_TYPE_NOT_USED` returned for axes that are not present in motion groups?

**Comment by ted-miller** [comment]
Ahhh... Yeah, I merged w/o testing. Foolish.

> is MOTION_TYPE_NOT_USED returned for axes that are not present in motion groups?

Yes. There's 8 axes in EVERY group. Most are not used.

**Comment by ted-miller** [comment]
> Should this just only look at axes which are actually configured:

Yes. But it's not terribly straight-forward. The current control-group doesn't have knowledge of the base-group's axis configuration.

So it'd be something like:
`g_Ros_Controller.ctrlGroups[group->baseTrackGroupIndex].axisType[i] != AXIS_INVALID`

This seems like an awful lot of clutter for something that _shouldn't_ happen and AFAICT _cannot_ happen. 

I'd be in favor of just adding a `default: break;` to the switch and removing the alarm. 
But I'll leave it up to you.

**Comment by gavanderhoorn** [comment]
See #179.
