### ISSUE TITLE
Cycle-switch-mode during setup procedure

### ISSUE THREAD

**Issue by ted-miller** [Yaskawa-Global/motoros2#203]
Re: https://github.com/Yaskawa-Global/motoros2/discussions/201#discussioncomment-8224715

Need to add this to setup procedure. Perhaps we can also detect this in real time via CIO.

(I vaguely recall this being an issue in the past. But I can't find anything about it in the repos.)

**Comment by ted-miller** [comment]
Looks like we can detect with these:

![image](https://github.com/Yaskawa-Global/motoros2/assets/4623811/a4f6aa51-f2fb-4b2d-9a63-79186457269f)

**Comment by gavanderhoorn** [comment]
@ted-miller: did we forget to add something to the setup documentation about this?

**Comment by ted-miller** [comment]
It looks like I added to the motoros1 wiki, but didn't do it here.

**Comment by ted-miller** [comment]
It just occurred to me that there is an API for mpSetCycle. 

@yai-rosejo @gavanderhoorn 

I vote that instead of documenting the step of setting cycle, we should automate it. Right after we enable servos, we can set cycle and then start the INIT_ROS job. 

Thoughts?

**Comment by gavanderhoorn** [comment]
Hm. Changing 'global' controller configuration for a single application in an automagic way?

Not sure.

**Comment by ted-miller** [comment]
It's not global. It's instantaneous.

When the user switches the key-switch, the robot's "saved" configuration is restored.

(At least I _think_ that's true. Need to verify.)

**Comment by gavanderhoorn** [comment]
If that's true (ie: it reverts) automating it seems like it would improve UX.

related btw: I've never had my YRC1 configured with continuous and never really ran into any issues. Was I just lucky?
