### ISSUE TITLE
Missing check for energy-savings mode

### ISSUE THREAD

**Issue by ted-miller** [Yaskawa-Global/motoros2#213]
Related to #114 
If we are already in `PointQueueMode` and `Ros_ServiceQueueTrajPoint_Trigger` is called after energy-savings mode kicks in, then it won't check for eco-mode.

**Comment by yai-rosejo** [comment]
Energy-savings mode kicks the system out of point_queue_mode. No specific change is required.
https://github.com/Yaskawa-Global/motoros2/blob/10d8f00317c5d4ef7960627962337bf72e2ba817/src/MotionControl.c#L1591-L1608
