### ISSUE TITLE
Readme troubleshooting references DX100 controller

### ISSUE THREAD

**Issue by ted-miller** [Yaskawa-Global/motoros2#25]
Just noticed this mentions DX100. Bad copy/paste from MotoROS1. 

https://github.com/Yaskawa-Global/motoros2/blob/5c63671df6c6905a5e5f0aa463bec18cef5087c8/doc/troubleshooting.md#alarm-8003100---111

I'll submit a fix later this afternoon.

**Comment by gavanderhoorn** [comment]
Technically it's not necessarily completely wrong, right? Just that we don't support DX100.

`DX100` is also mentioned in the text for `8003[10]` and `4430[6]`

**Comment by ted-miller** [comment]
I think the 4430[6] one is valid to keep in 

> This alarm occurs if you run the DX100 version of the `INIT_ROS` Inform job on a non-DX100 controller.
> Please delete the `INIT_ROS` job from your pendant and replace it with the version for all other controllers.
