### ISSUE TITLE
MicroROS ros_domain_id issue

### ISSUE THREAD

**Issue by luke-reframe** [Yaskawa-Global/motoros2#267]
### Discussed in https://github.com/Yaskawa-Global/motoros2/discussions/266

<div type='discussions-op-text'>

<sup>Originally posted by **luke-reframe** June 20, 2024</sup>
Hello,

Upon changing the ros_domain_id field in my motoros2_config.yaml away from the default, microROS has entirely stopped working. I have confirmed through the debug listener that both the host and the controller are using the correct ros_domain_id (5) though microROS continues to crash upon connection. It should be noted that I had no issues with connecting, listing nodes/topics, and sending actions via the FollowJointTrajectory action server prior to this.

I am using a yrc1000micro controller with an HC10DT running Humble 0.1.2.

Here is my config
[motorosconfig.txt](https://github.com/user-attachments/files/15918437/motorosconfig.txt)

Debug log:
[DebugLog620.txt](https://github.com/user-attachments/files/15918438/DebugLog620.txt)

and the docker command I have been using to run microROS with associated output (same run as the Debug log):
[dockercommand.txt](https://github.com/user-attachments/files/15918478/dockercommand.txt)

Note that I have attempted to run both commands:
`docker run   -it   --rm   --net=host   --user=$(id -u):$(id -g)   microros/micro-ros-agent:humble     udp4     --port 8888
`
and
`docker run -it --rm --net=host --user=$(id -u):$(id -g) -e ROS_DOMAIN_ID=5 microros/micro-ros-agent:humble udp4 --port 8888
`
both resulting in the same error. The first command is the one I have been successfully using with ros_domain_id 0.</div>

**Comment by ted-miller** [comment]
I'm closing this issue to avoid confusion with the open discussion, #266. 
If we identify a problem with the MotoROS2 software, we'll re-open this.
