### ISSUE TITLE
MotoROS2: Fatal Error (subcode: 10)

### ISSUE THREAD

**Issue by DocVaughan** [Yaskawa-Global/motoros2#291]
First, thank you for the package. We have it running on three GP12s and a GP7. The GP12s are running beautifully. However, the GP7 frequently has a `MotoROS2: Fatal Error (subcode: 10)`. Anecdotally, it seems to be happening with more frequency over time. I've attached the `CMOS.BIN` file, the `PANELBOX.LOG`, our config file, and the log from the debug listener during controller startup.

We're on Humble and have seen the same issue on both 0.1.2 and 0.1.3. 

Thank you in advance for any guidance you can provide.

* [CMOS.zip](https://github.com/user-attachments/files/16661020/CMOS.zip)
* [PANELBOX.LOG](https://github.com/user-attachments/files/16661125/PANELBOX.LOG)
* [motoros2_config.yaml.zip](https://github.com/user-attachments/files/16661036/motoros2_config.yaml.zip)
* [20240819T095502_motoros2_debug_log.txt](https://github.com/user-attachments/files/16661188/20240819T095502_motoros2_debug_log.txt)

**Comment by gavanderhoorn** [comment]
> the GP12s are running beautifully. However, the GP7 frequently has a `MotoROS2: Fatal Error (subcode: 10)`.

do the GP12s also have additional axes? And are those also calibrated against the main robot (ie: `r1`)?

**Comment by DocVaughan** [comment]
Two of the GP12s also have a postioner. One does not. For the two with positioners, they are calibrated like the GP7.

**Comment by ted-miller** [comment]
> Anecdotally, it seems to be happening with more frequency over time

How frequent would you estimate? 

I have loaded your CMOS and rebooted 5 or 6 times without receiving that alarm. Given that this doesn't occur every time on your system either, my first suspect would be the networking layer. I suggest checking all connections and make sure that there aren't any IP conflicts. Additionally, double check the version of the microROS Agent on your PC. Make sure that it's the latest humble version.

--------------------------------

Also, the panelbox.log indicates that you don't have the arc-welding applications installed (which is good). But given how your robot was configured initially, I just want to emphasize that Simple Connect and UWI must not be installed alongside MotoROS2.
