### ISSUE TITLE
Verify new cfg file (on CN102) is valid YAML before overwriting current cfg

### ISSUE THREAD

**Issue by gavanderhoorn** [Yaskawa-Global/motoros2#31]
The [current implementation](https://github.com/Yaskawa-Global/motoros2/blob/08329e5a1646315bffb5effdb40857eaea343523/src/ConfigFile.c#L356-L439) of `Ros_ConfigFile_CheckUsbForNewConfigFile()` copies and renames the new `.yaml` file it finds on `CN102` without verifying it is valid YAML.

If the new file is corrupt or contains contents that `libyaml` can't parse, this leaves MotoROS2 without a valid configuration file.

We should instead verify the new `.yaml` on the USB stick can be parsed and only then overwrite the SRAM file.

If parsing fails, post an alarm, do not overwrite anything.

This would result in the old settings remaining active, but in some cases this could actually help as at least MotoROS2 would not throw away a potentially working configuration.

**Comment by gavanderhoorn** [comment]
The [update procedure for post `YAS4.70`/`YBS3.02`](https://github.com/Yaskawa-Global/motoros2/tree/08329e5a1646315bffb5effdb40857eaea343523#controller-software-yas470-or-ybs302-or-later) doesn't use a USB stick in `CN102` any more.

That would seem to make the workflow described in the OP difficult/impossible.

**Comment by ted-miller** [comment]
> That would seem to make the workflow described in the OP difficult/impossible.

Agreed. 
Although this may be useful on older controller software, I don't think that it is worth the effort since this won't be the preferred/suggested workflow going forward.

I'm going to go ahead and close this. Feel free to reopen if someone feels like it's benefcial.
