### ISSUE TITLE
Fix print format for final positions outside of tolerance

### ISSUE THREAD

**Issue by jimmy-mcelwain** [Yaskawa-Global/motoros2#343]
Related to https://github.com/Yaskawa-Global/motoros2/issues/233 and https://github.com/Yaskawa-Global/motoros2/pull/241. 

@ted-miller said 
>The debug broadcasts are not printing doubles properly. We ran some tests that multiplied the values by 1000 and then cast as an int. The integer displays as expected. So we'll need to investigate vsnprintf behavior some more.

I am not having any problems with the debug broadcast printing doubles. But I did notice that in the code below, the format specifier is `%d` (decimal) even though `violators` is an array with members of type `double`. 

https://github.com/Yaskawa-Global/motoros2/blob/9f5ccf6dcf86cb3be340c850cb3aa990aa9c4bd6/src/ActionServer_FJT.c#L706-L708

That change was made in commit https://github.com/Yaskawa-Global/motoros2/commit/742e4fc07b0ba03cf534fb98c4522faf809a4578 which is a part of https://github.com/Yaskawa-Global/motoros2/pull/241. 

I am not sure if that comment was written using the branch that used `%d`. But I believe that the change to `%d` was a mistake, and that it should be changed back to print a floating point value. Maybe it should be changed to `%.5f` rather than the `%.4f` that it was before.

**Comment by gavanderhoorn** [comment]
yes, that was changed to `%d` because of the "then cast as an int".

If the scaling isn't performed anymore, the specifier should be reverted to `%f` again.

**Comment by jimmy-mcelwain** [comment]
> If the scaling isn't performed anymore, the specifier should be reverted to `%f` again.

I double checked and no scaling is performed anymore. #345 is straightforward and will fix the problem.
